// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card-content': string;
  'card-header': string;
  'card-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
