// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'l': string;
  'm': string;
  's': string;
  'xl': string;
}
export const cssExports: CssExports;
export default cssExports;
