// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-form': string;
  'list': string;
  'list-content': string;
  'list-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
