name: 06-todoapp deploy
on:
  push:
    branches:
      - master
    paths:
      - '**.yaml'
      - '06-todoapp/**.tsx'
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install
        run: cd ./06-todoapp && yarn
      - name: build
        run: cd ./06-todoapp && yarn build
      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: todoapp
          FOLDER: 06-todoapp/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}